# Generated by Django 3.1.2 on 2020-10-07 08:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_time_to_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, help_text='Slug will be generated automatically from the title of the post', populate_from='title', unique_with=('title',)),
        ),
    ]
